name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'  # Cambia esto a la versión de Java que necesitas
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get 5 characters of last commit
      run: echo "COMMIT_HASH=${GITHUB_SHA::5}" >> $GITHUB_ENV

    - name: Extract version from pom.xml
      id: extract_version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: \src\main\docker\Dockerfile.jvm
        push: true
        tags: angelaranda04/quarkus-prueba:${{ steps.extract_version.outputs.version }}-${{ env.COMMIT_HASH }}
      
    
    
        
   
