name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'  # Cambia esto a la versión de Java que necesitas
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get 5 characters of last commit
      run: echo "COMMIT_HASH=${GITHUB_SHA::5}" >> $GITHUB_ENV
      
    - name: Build Docker Image
      id: build_image
      run: |
        - MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        - echo $MVN_VERSION
        IMAGE_TAG="$MVN_VERSION-${{ env.COMMIT_HASH }}"
        
        docker buildx create --use
        docker buildx build -f .\src\main\docker\Dockerfile.jvm -t angelaranda04/quarkus-prueba:$IMAGE_TAG .
      
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
        
        - MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        - echo $MVN_VERSION
        IMAGE_TAG="$MVN_VERSION-${{ env.COMMIT_HASH }}"
        
        docker push angelaranda04/quarkus-prueba:$IMAGE_TAG
    
        
   
